name: CI

permissions:
  pull-requests: write
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: "node_modules"
          key: npm-${{ hashFiles('package-lock.json') }}
      - run: npm install
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run format
